import { Montserrat } from 'next/font/google'
import "./globals.css";

 
// If loading a variable font, you don't need to specify the font weight
const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={montserrat.className + " antialiased bg-[#fff5f1] max-w-[1050px] mx-auto px-6 lg:px-16"}
      >
        {children}
      </body>
    </html>
  );
}
